# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38db7cec5d4db7e12ecaa522e3660e363534c47d850883f2cf1e8ddf80e009816e816fa19ec987f87a9c341b56fe037c673f4b85af2016635f30181c68aa4168

test:
  secret_key_base: ee5c7555bf6992ae620e3df21303d969a46dc725a1ef06d764cab84cd957e7241a014f0f43a9a2098dad61feaf5d58b8267c293321b9b7bec4363583479bc108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
